apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pg-app
  template:
    metadata:
      labels:
        app: pg-app
    spec:
      containers:
      - name: pg-app
        image: app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: PGDATABASE
          valueFrom:
            configMapKeyRef:
              name: pg-app-config
              key: PGDATABASE 
        - name: PGPOOL_HOST
          valueFrom:
            configMapKeyRef:
              name: pg-app-config
              key: PGPOOL_HOST

