apiVersion: v1
kind: Service
metadata:
  name: pg-app-service
spec:
  selector:
    app: pg-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort  # or LoadBalancer if your environment supports it

